### ISSUE TITLE
Adding some parameters to the User

### ISSUE THREAD

**Issue by BryanMoslo** [gobuffalo/buffalo-auth#1]
It would be good to have an option to create some other parameters to the user apart of Email, PasswordHash, Password and PasswordConfirmation, from the buffalo generate command, something like:

`$ buffalo generate auth first_name last_name address`

on that way we don't have to create another migration to add those parameters to the User. What do you think?

**Comment by markbates** [comment]
Absolutely! Bring on the PR. :)

**Comment by paganotoni** [comment]
I'm up to work on this one.
