### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo-auth#2]
One of the things i would like to add into buffalo auth is password recovery, my intention is to have something like:

```
$ buffalo g auth password-recovery
```

That would:

- Add properties on the User model:
  - `PasswordRecoveryToken` (nulls.String) property
  - `PasswordRecoveryValidUntil` (nulls.Time) property
- Add a method to re-generate PasswordRecoveryToken and ValidUntil on User model.
- Add 2 actions to `actions/auth.go`:
  - One to render the password recovery form [GET] /password-recovery
  - One to handle the recovery request, [POST] /password-recovery
- Add 1 mailer for for the password recovery request that will be used by the recovery request handler.

**Comment by paganotoni** [comment]
cc @markbates

**Comment by paganotoni** [comment]
@markbates LMK when you have the chance to read this.

**Comment by mclark4386** [comment]
This is something I've been hoping would be added for a while, but haven't had time to do it myself, so my vote is go for it^^

**Comment by kteb** [comment]
Yeah I agree it'll be cool. A very similar one for validating the email when subscribing could be also cool (I can do it if you want ;) ), it was on my plan to propose it.
