### ISSUE TITLE
Move to gofrs/uuid

### ISSUE THREAD

**Issue by paganotoni** [gobuffalo/buffalo-auth#31]
Currently buffalo-auth using deprecated `gobuffalo/uuid`

**Comment by stanislas-m** [comment]
We can't do that until https://github.com/gofrs/uuid/issues/61 is solved.

**Comment by ghost** [comment]
Hi @stanislas-m, saw your mention and wanted to let you know that gofrs/uuid@3.2.0 was cut to solve the aforementioned issue.

**Comment by paganotoni** [comment]
Covered by v1.0.8 in #57
