### ISSUE TITLE
Buffalo-auth fails to go-get, no component to generate

### ISSUE THREAD

**Issue by raqbit** [gobuffalo/buffalo-auth#33]
When I try to install bufallo-auth:

`go get -u github.com/gobuffalo/buffalo-auth`

```
...
go: downloading golang.org/x/sys v0.0.0-20190222072716-a9d3bda3a223
go: finding github.com/gobuffalo/genny/movinglater/plushgen latest
go: finding github.com/gobuffalo/genny/movinglater latest
go build github.com/gobuffalo/genny/movinglater/plushgen: no Go files in 
```

`buffalo g auth` > Shows buffalo generate help menu without any mention of `auth`.

I am using go modules (`GO111MODULE=on`) and running the first command in my project directory.

`go version`: `go version go1.11.5 linux/amd64`

`buffalo version`: `Buffalo version is: v0.14.0 `

**Comment by raqbit** [comment]
`buffalo-auth auth` is working.

**Comment by owen2345** [comment]
Hey @Raqbit 
How did you fix the problem?

**Comment by raqbit** [comment]
I was not able to use `buffalo g auth`, but I was able to use `buffalo-auth`, which is a binary located in `$GOPATH/bin`. I think this might be used under the hood by  `buffalo g auth`.

**Comment by owen2345** [comment]
You are right, thank you!

**Comment by markbates** [comment]
Plugins need to be installed into your application before you can use them https://www.gobuffalo.io/en/docs/plugins#installing-plugins
