### ISSUE TITLE
after installing plugins and buffalo-auth runnning buffalo g auth does nothing

### ISSUE THREAD

**Issue by tadeogutierrez** [gobuffalo/buffalo-auth#40]
After installing plugins and buffalo-auth, runnning buffalo g auth does nothing on windows. Auth does not show on buffalo plugins list:
$ buffalo g auth
Generate application components

Usage:
  buffalo generate [command]

Aliases:
  generate, g

Available Commands:
  action      Generate new action(s)
  mailer      Generate a new mailer for Buffalo
  plugin      [PLUGIN] generates a new buffalo plugin
  resource    Generate a new actions/resource file
  task        Generate a grift task

Flags:
  -h, --help   help for generate

Use "buffalo generate [command] --help" for more information about a command.

**Comment by mrkmcknz** [comment]
Hi @tadeogutierrez usually this happens when you forget to install the plugin into your project. Try running `buffalo plugins install github.com/gobuffalo/buffalo-auth` and then `buffalo plugins list` to confirm that buffalo-auth is installed on the project.

**Comment by jay13jay** [comment]
I have having this issue too. Even after installing the plugin, it's not showing up under plugins list:

`$  buffalo plugins list
Bin |Command |Description
--- |---     |---`


But it IS showing up in the plugins config:
`$ cat config\buffalo-plugins.toml
[[plugin]]
  binary = "buffalo-auth"
  go_get = "github.com/gobuffalo/buffalo-auth"

[[plugin]]
  binary = "buffalo-pop"
  go_get = "github.com/gobuffalo/buffalo-pop"`


Any help would be appreciated. If I'm not mistaken, this seems to be related to the plugins plugin being merged into the main package, but I'm not 100% sure on that

**Comment by jay13jay** [comment]
I do not know if this is the proper way to do it, but I did get the generator to work by using the following:
`
buffalo-auth auth
`

If this is the proper way, fine by me, but it doesn't feel right to me

**Comment by paganotoni** [comment]
@tadeogutierrez This seems to be because you need to install the plugin in your app with:
```
buffalo plugins install github.com/gobuffalo/buffalo-auth
```
Then buffalo will be able to run`buffalo g auth` within your app.
