### ISSUE TITLE
go get: error loading module requirements

### ISSUE THREAD

**Issue by Niklao** [gobuffalo/buffalo-auth#41]
I am on latest release of Go And Buffalo 
Follwing is the output of installation
Is this due to some outdated dependencies???
Following is the output :

> go get -u  github.com/gobuffalo/buffalo-auth
> go: finding github.com/gobuffalo/attrs latest
> go: finding github.com/serenize/snaker latest
> go: finding golang.org/x/crypto latest
> go: finding github.com/gobuffalo/meta latest
> go: finding golang.org/x/sync latest
> go: finding github.com/gobuffalo/logger latest
> go: finding golang.org/x/tools latest
> go: finding github.com/gobuffalo/licenser latest
> go: finding github.com/markbates/oncer latest
> go: finding github.com/sourcegraph/syntaxhighlight latest
> go: finding github.com/ugorji/go/codec latest
> go: finding golang.org/x/sys latest
> go: finding github.com/armon/consul-api latest
> go: finding golang.org/x/net latest
> go: finding github.com/gobuffalo/gitgen latest
> go: finding github.com/sourcegraph/annotate latest
> go: finding github.com/gobuffalo/helpers latest
> go: finding github.com/gobuffalo/syncx latest
> go: finding github.com/google/pprof latest
> go: finding gopkg.in/tomb.v1 latest
> go: finding gopkg.in/check.v1 latest
> go: finding golang.org/x/lint latest
> go: finding github.com/shurcooL/highlight_diff latest
> go: finding google.golang.org/genproto latest
> go: finding github.com/prometheus/procfs latest
> go: finding github.com/shurcooL/go latest
> go: finding github.com/golang/glog latest
> go: finding golang.org/x/oauth2 latest
> go: finding golang.org/x/build latest
> go: finding github.com/anmitsu/go-shlex latest
> go: finding github.com/shurcooL/octicon latest
> go: finding github.com/jellevandenhooff/dkim latest
> go: finding honnef.co/go/tools latest
> go: finding github.com/googleapis/gax-go v2.0.2+incompatible
> go: finding github.com/shurcooL/home latest
> go: finding github.com/neelance/astrewrite latest
> go: finding github.com/tarm/serial latest
> go: finding github.com/shurcooL/go-goon latest
> go: finding github.com/shurcooL/github_flavored_markdown latest
> go: finding github.com/shurcooL/events latest
> go: finding dmitri.shuralyov.com/html/belt latest
> go: finding dmitri.shuralyov.com/service/change latest
> go: finding github.com/shurcooL/notifications latest
> go: finding dmitri.shuralyov.com/state latest
> go: finding github.com/shurcooL/users latest
> go: finding github.com/bradfitz/go-smtpd latest
> go: finding github.com/gregjones/httpcache latest
> go: finding golang.org/x/time latest
> go: finding github.com/shurcooL/highlight_go latest
> go: finding github.com/shurcooL/httpgzip latest
> go: finding github.com/shurcooL/gofontwoff latest
> go: finding github.com/shurcooL/httpfs latest
> go: finding github.com/coreos/go-systemd latest
> go: finding github.com/shurcooL/httperror latest
> go: finding github.com/golang/lint latest
> go: finding github.com/flynn/go-shlex latest
> go: github.com/golang/lint@v0.0.0-20190409202823-959b441ac422: parsing go.mod: unexpected module path "golang.org/x/lint"
> go: sourcegraph.com/sourcegraph/go-diff@v0.5.1: parsing go.mod: unexpected module path "github.com/sourcegraph/go-diff"
> go: finding golang.org/x/tools v0.0.0-20190114222345-bf090417da8b
> go: finding github.com/shurcooL/issues latest
> go: finding github.com/shurcooL/reactions latest
> go: finding github.com/shurcooL/gopherjslib latest
> go: finding github.com/shurcooL/issuesapp latest
> go: finding golang.org/x/perf latest
> go get: error loading module requirements

**Comment by frederikhors** [comment]
Execute `go get -u github.com/gobuffalo/buffalo-auth` outside project folder.

If it works please close this issue.

**Comment by jameswang2015** [comment]
I get the same issue, and I run go get command at $HOME folder. Please advise. 
`zwang-mac:~ zwang$ go get gitlab.vm.domaintools.net/backend/gatheringsystem/remington
go: finding gitlab.vm.domaintools.net/backend/gatheringsystem/remington latest
go: finding github.com/beorn7/perks v1.0.1
go: finding github.com/googleapis/gax-go/v2 v2.0.5
go: finding golang.org/x/sys v0.0.0-20190507160741-ecd444e8653b
go: finding golang.org/x/sys v0.0.0-20190801041406-cbf593c0f2f3
go: finding golang.org/x/sys v0.0.0-20190509141414-a5b02f93d862
go: finding golang.org/x/net v0.0.0-20190503192946-f4e77d36d62c
go: finding golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: finding golang.org/x/tools v0.0.0-20190506145303-2d16b83fe98c
go: finding google.golang.org/appengine v1.5.0
go: finding golang.org/x/lint v0.0.0-20190409202823-959b441ac422
go: finding golang.org/x/net v0.0.0-20190108225652-1e06a53dbb7e
go: finding github.com/hashicorp/golang-lru v0.5.1
go: finding github.com/knq/sysutil v0.0.0-20181215143952-f05b59f0f307
go: finding github.com/gobwas/httphead v0.0.0-20180130184737-2c6c146eadee
go: finding github.com/golang/mock v1.3.1
go: finding go.opencensus.io v0.21.0
go: finding honnef.co/go/tools v0.0.0-20190418001031-e561f6794a2a
go: finding cloud.google.com/go v0.34.0
go: finding google.golang.org/api v0.8.0
go: finding rsc.io/binaryregexp v0.2.0
go: finding github.com/json-iterator/go v1.1.7
go: finding gitlab.vm.domaintools.net/backend/gatheringsystem/gatherc/v3 v3.3.2
go: finding cloud.google.com/go v0.38.0
go: gitlab.vm.domaintools.net/backend/gatheringsystem/gatherc/v3@v3.3.2: unknown revision gatherc/v3.3.2
go: finding github.com/gobwas/pool v0.2.0
go: finding github.com/gobwas/ws v1.0.0
go: finding google.golang.org/genproto v0.0.0-20190801165951-fa694d86fc64
go: finding go.opencensus.io v0.22.0
go: finding golang.org/x/tools v0.0.0-20190628153133-6cdbf07be9d0
go: finding github.com/google/pprof v0.0.0-20190515194954-54271f7e092f
go: finding cloud.google.com/go/datastore v1.0.0
go: finding github.com/mailru/easyjson v0.0.0-20180823135443-60711f1a8329
go: finding github.com/jstemmer/go-junit-report v0.0.0-20190106144839-af01ea7f8024
go: finding google.golang.org/genproto v0.0.0-20190502173448-54afdca5d873
go: finding google.golang.org/grpc v1.21.1
go: finding google.golang.org/grpc v1.20.1
go: finding github.com/mailru/easyjson v0.0.0-20190403194419-1ea4449da983
go: finding github.com/google/martian v2.1.0+incompatible
go: finding golang.org/x/exp v0.0.0-20190510132918-efd6b22b2522
go: error loading module requirements`

**Comment by sio4** [comment]
outdated. closing, but please feel free to reopen the issue if someone need help for the same issue.
