### ISSUE TITLE
Proposal: Add JWT support to buffalo-auth

### ISSUE THREAD

**Issue by tsmith1024** [gobuffalo/buffalo-auth#45]
Would there be value in integrating JWT support directly into the buffalo-auth plugin, or would that be better suited for a separate plugin to be installed/used when needed? I can understand either case but wanted to propose it here.

My thought is to leave the current behavior of the auth generation as the default, with an additional option to execute it in JWT mode.

As a note, I recently worked on a plugin for JWT auth setup that should (hopefully) be mostly reusable, found here: https://github.com/MotionMobs/buffalo-token-auth

Thanks for thoughts on this!

**Comment by sio4** [comment]
I am not fully sure but I feel like your proposal is more likely about the JWT support for authentication (which is already provided by https://github.com/gobuffalo/mw-tokenauth).

While the buffalo plugins (that is named with `buffalo-` prefix) expand CLI so users could have more rich tools for their development (so the final output of them is not feature support but a scaffold code), the buffalo middlewares (which is named with `mw-` prefix) will provide more features that could be used as a kind of application's plugins.

Please take a look at the middleware module I linked above, and let us know if there is any gap between your intention and the middleware. (I will close this issue for now)
