### ISSUE TITLE
Create "signin.html" instead "index.html" replacing

### ISSUE THREAD

**Issue by frederikhors** [gobuffalo/buffalo-auth#47]
I think `buffalo g auth` should not replace the `index.html` file automatically generated by buffalo but instead create a `signin.html` file.

**Comment by draco2003** [comment]
+1 on not overwriting index.html file. 
Ideally we would create a route that either shows the current user details or handles the unauthorized request (redirects to the sign-in page for web and responds with unauthorized for api?)

**Comment by paganotoni** [comment]
This one is solved in #64
