### ISSUE TITLE
go get error (genny)

### ISSUE THREAD

**Issue by nicomo** [gobuffalo/buffalo-auth#69]
Not sure what's happening, but while outside of any particular project, I have an error when go getting this package :
 
```
go get -u github.com/gobuffalo/buffalo-auth
# github.com/gobuffalo/buffalo-auth/genny/auth
go/src/github.com/gobuffalo/buffalo-auth/genny/auth/auth.go:59:25: multiple-value meta.New() in single-value context
go/src/github.com/gobuffalo/buffalo-auth/genny/auth/auth.go:59:26: cannot use "." (type string) as type here.Info in argument to meta.New
```

Then in a project `buffalo plugins install github.com/gobuffalo/buffalo-auth` exits with the same message and status 2.

On go version go1.13 darwin/amd64 and Buffalo version is: v0.15.4

Any help appreciated, thanks.

**Comment by DomasB** [comment]
Having exactly the same issue.
Go version: 1.13.6 linux/amd64
Buffalo version: v0.15.4

Also, if I run the same command in my project folder, I get
```
../../../../pkg/mod/github.com/gobuffalo/buffalo-auth@v1.2.0/genny/auth/auth.go:62:36: cannot use ctx (type *"github.com/gobuffalo/plush".Context) as type *"github.com/gobuffalo/plush/v4".Context in argument to plushgen.Transformer
```

**Comment by pablotrianda** [comment]
Having the same issue here!

Go version go1.13.7 linux/amd64
Buffalo version is: v0.15.5 

`# github.com/gobuffalo/buffalo-auth/genny/auth`

`src/github.com/gobuffalo/buffalo-auth/genny/auth/auth.go:59:25: multiple-value meta.New() in single-value context`

`src/github.com/gobuffalo/buffalo-auth/genny/auth/auth.go:59:26: cannot use "." (type string) as type here.Info in argument to meta.New`

I have created the buffalo app with the --api flag, may be this cause the problem?

**Comment by nicomo** [comment]
> I have created the buffalo app with the --api flag, may be this cause the problem?

Didn't use the --api flag in my case, so probably not the cause of the problem.

**Comment by sio4** [comment]
Obsolete, the issue must be related to the `GOPATH` mode and now we only support go modules.

Additional information: The interface of `meta` (v0.x, which is under the `v0` branch now) and the interface of `meta/v2` (currently in `master` branch) are different and all of the current buffalo family projects still use v0.

* `multiple-value meta.New() in single-value context` --> v2's `New()` retuns two values while v0 returns only one.
* `cannot use "." (type string) as type here.Info in argument to meta.New` v2 has argument `here.Info` while v0 gets `string`.

Closing.
