### ISSUE TITLE
Compatibility issues when integrating with buffalo 0.16.3

### ISSUE THREAD

**Issue by L1ghtman2k** [gobuffalo/buffalo-auth#77]
Not sure if this is a bug, or I am just doing something wrong. I started a clean setup on ubuntu, with latest buffalo. I implemented localauth as suggested by https://gobuffalo.io/en/docs/auth/. When I start `buffalo dev` and attempt to sign up a user by going to /users/new it gives me the following when I submit the form:
![image](https://user-images.githubusercontent.com/35672535/79038138-f5fbe300-7ba4-11ea-8055-784d369ec751.png)

UPD:
I fixed by changing all instances of `github.com/gobuffalo/pop` to `github.com/gobuffalo/pop/v5` and `github.com/gobuffalo/validate` to `github.com/gobuffalo/validate/v3`

Can anyone look into this? I am still not sure if this is a bug or a user error

**Comment by L1ghtman2k** [comment]
This might be related to https://github.com/gobuffalo/buffalo/issues/1886

**Comment by paganotoni** [comment]
Running `buffalo fix` after generating the auth code should solve the issue.
