### ISSUE TITLE
Feature request: Password salts

### ISSUE THREAD

**Issue by L1ghtman2k** [gobuffalo/buffalo-auth#78]
Hey, 

I was wondering if there are any plans to implement password salting?

**Comment by paganotoni** [comment]
Hey @L1ghtman2k 👋, I don't think we've discussed adding password salts. Do you have an idea on what would be expected there ? Thanks!

**Comment by L1ghtman2k** [comment]
After doing some research I realized that buffalo already implements that by default. 

generateHash() function uses bcrypt's GenerateFromPassword function which puts both cost, password hash, and the salt into the hash.
