### ISSUE TITLE
interface {} is *pop.Connection, not *pop.Connection

### ISSUE THREAD

**Issue by xinglixing** [gobuffalo/buffalo-auth#79]
follow the auth setup steps. When creating a new user got the error -interface conversion: interface {} is *pop.Connection, not *pop.Connection (types from different packages).
Buffalo version is: v0.16.8

**Comment by atakanyenel** [comment]
Hey, I had the same error. See https://github.com/gobuffalo/buffalo/issues/1982#issuecomment-626982190 

You can workaround this error by running `buffalo fix`

**Comment by vineetdaniel** [comment]
had the same error. `buffalo fix` fixed it

**Comment by ghost** [comment]
Thanks guys! The issue fixed.
