### ISSUE TITLE
`buffalo g auth` needs an update

### ISSUE THREAD

**Issue by ernsheong** [gobuffalo/buffalo-auth#82]
- `form_for` -> `formFor`
- Replace untagged dependencies with tagged dependencies (e.g. replace `github.com/gobuffalo/validate` with `github.com/gobuffalo/validate/v3`, etc.
- etc.

An update is needed for `buffalo g auth` to work seamlessly with latest Buffalo. Also, https://github.com/gobuffalo/buffalo-auth/issues/67

**Comment by rayjanoka** [comment]
lots of issues getting off the ground, but I got it. 

this post helped, make sure to update all your imports to match these:
```
  "github.com/gobuffalo/pop/v6"
  "github.com/gobuffalo/validate/v3"
  "github.com/gobuffalo/validate/v3/validators"
```

**Comment by NurfitraPujo** [comment]
Thanks, this post really helped me

**Comment by sio4** [comment]
Hi,

Thanks for the posts! Actually, this issue was addressed when we were updating all module dependencies last winter, but I found we missed releasing a new version! I will check some more and will proceed with it! Thanks!
